### ISSUE TITLE
Not all single element arrays need to be converted to just the element.

### ISSUE THREAD

**Issue by ghost** [superseriousbusiness/activity#18]
https://github.com/superseriousbusiness/activity/blob/main/streams/impl/jsonld/property_type/gen_property_jsonld_type.go#L547

I found this because I received an activity from a gotosocial instance that has it's "tag" property as a single tag, and not an array containing tags.

received:
`"tag" : {"href": "value", "name": "value", "type": "Hashtag" }`
expected:
`"tag" : [ {"href": "value", "name": "value", "type": "Hashtag" } ]`

**Comment by tsmethurst** [comment]
Closing this because that's valid JSON-LD. If tag was an OrderedCollection it would be another story, but it's not.
